### ISSUE TITLE
Plots now showing

### ISSUE THREAD

**Issue by engelberger** [napoles-uach/stmol#39]
Hello, I was wondering if you have the issue of the viewer not rendering, I have tested in multiple web browsers (Chrome, Firefox, Edge)and none is working. I can not see the stmol viewers in https://rascore.streamlit.app/ either. An hour ago a bugfix was commited 
https://github.com/3dmol/3Dmol.js/issues/636 but still not working.

Thanks in advance

**Comment by dkoes** [comment]
3Dmol.js 2.0 no longer provides JQuery and if you are using the UI you'll need to explicitly include 3Dmol.ui.js.  If you are generating HTML from jupyter notebooks, you'll need to update py3Dmol to the latest version and regenerate.

**Comment by engelberger** [comment]
Thanks, running the following to update py3Dmol solved the issues

`pip install py3Dmol==2.0.0.post2`

**Comment by mitch-parker** [comment]
Thank you so much for the solution!
