### ISSUE TITLE
No module named 'stmol'

### ISSUE THREAD

**Issue by emarsh25** [napoles-uach/stmol#41]
Potentially a user error but I am trying to use stmol and every time I start my streamlit app, I just get an error saying I don't have a module named stmol. I have definitely installed it because I can see it on my pip list. Any idea what the problem might be? I am running on a Mac Pro M1.

**Comment by napoles-uach** [comment]
Hi Evan, this is strange. Could you try to install py3dmol in this way?
pip install py3Dmol==2.0.0.post2

Not sure if this will solve your issue.

**Comment by emarsh25** [comment]
Thanks for reaching out. I am not sure what the problem was but it went away. I rebuilt my environment and then it was fine. I don't know if there was a clash in packages or what but it is working now. Thank you!

**Comment by napoles-uach** [comment]
Glad to know that!
