### ISSUE TITLE
Dependency error (bug and fix)

### ISSUE THREAD

**Issue by Lucandia** [napoles-uach/stmol#44]
If I try to use stmol I get the error 
"ModuleNotFoundError: No module named 'ipython_genutils'"
This error happens also in the demo web app.
Adding ipython_genutils to the requirements fixes the error.
After adding the dependency the web app works properly: https://stmol3d.streamlit.app/

**Comment by napoles-uach** [comment]
Thanks @Lucandia, let me check this!
